<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonHitungSimulasiBekas</name>
   <tag></tag>
   <elementGuidId>4d8ee0f1-f194-4590-941c-5cc0806a0c14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-simulasiBudgetMobilBekas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-simulasiBudgetMobilBekas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>552f8ff3-7106-47b8-a3a9-8a385502effe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>green mt-3</value>
      <webElementGuid>3b5b6d2d-68d2-4712-9c67-c0c154bb8134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-simulasiBudgetMobilBekas</value>
      <webElementGuid>6a5311a1-7967-4b76-9890-5f5442ec9e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung Simulasi</value>
      <webElementGuid>3f8c7a75-efe6-4410-b911-c75780d3dfa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-simulasiBudgetMobilBekas&quot;)</value>
      <webElementGuid>79fc0176-3667-4d7e-89ce-27125ba501cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-simulasiBudgetMobilBekas']</value>
      <webElementGuid>c547cc65-a486-4bc2-91db-af75cf85d217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobil-bekas']/button</value>
      <webElementGuid>ddee72a1-047c-4349-b001-8d638d90e0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zona Wilayah belum dipilih.'])[2]/following::button[1]</value>
      <webElementGuid>8c889d90-e408-4575-8e35-61b6da701fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zona Wilayah'])[2]/following::button[1]</value>
      <webElementGuid>1981c062-bbd7-455b-a522-818912d3a7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIMULASI'])[1]/preceding::button[1]</value>
      <webElementGuid>60712b7d-0220-4588-8e83-deebaba5dcf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KREDIT'])[1]/preceding::button[1]</value>
      <webElementGuid>f3069466-89e0-4871-afad-c7f72bfbd3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/button</value>
      <webElementGuid>db19680f-1d83-4029-a1be-96b9c2f95395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-simulasiBudgetMobilBekas' and (text() = 'Hitung Simulasi' or . = 'Hitung Simulasi')]</value>
      <webElementGuid>740ed449-7da6-4017-ae68-95d8ae325473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
