<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HargaKendaraan</name>
   <tag></tag>
   <elementGuidId>9e2ed36b-5193-4b24-a14f-502250bd2bf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hargaKendaraan-Baru</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hargaKendaraan-Baru']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75b43f60-cd30-4243-acc1-35b57a5ed0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hargaKendaraan-Baru</value>
      <webElementGuid>43ff3d1c-7a77-48de-ad85-00cf8c3ee12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rp 0,00</value>
      <webElementGuid>80732444-5860-4c6b-9c4c-0e3153fb9db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>269f8d58-988d-47d1-8f02-2bdd0334a404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>045f27da-624d-4fef-a611-0f1f2a6537fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> curencyformat form-control</value>
      <webElementGuid>5c34ce9d-510a-46d6-b77e-c5711aa6531b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>48a73394-ad76-42ee-b38f-2eb693b82ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hargaKendaraan-Baru&quot;)</value>
      <webElementGuid>e9a4ab88-6447-4ea1-b325-89301b644c7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hargaKendaraan-Baru']</value>
      <webElementGuid>1dc1c47b-4054-4670-8101-93b05201615b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobil-baru']/div/div/div/input</value>
      <webElementGuid>05a261bf-abe4-44c2-b0e2-a96a94f5ceb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>4ec08c14-2f3e-44b1-a33b-f2d9adac2911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hargaKendaraan-Baru' and @placeholder = 'Rp 0,00' and @type = 'text']</value>
      <webElementGuid>93d7e992-d7cf-48a7-9fc5-140717d40cf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
