<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HargaKendaraanMobilBekas</name>
   <tag></tag>
   <elementGuidId>7bbe9d41-22f0-455f-80f3-58fb5c0321fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hargaKendaraan-Bekas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hargaKendaraan-Bekas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c3c8986-02b7-43fb-8325-f3a2dd47e79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74e9f270-7252-4518-b980-3ff9adb4c176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>c6423308-e6af-4764-a577-e42bf98b794b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rp 0,00</value>
      <webElementGuid>d358aa97-8894-4794-8502-500f0052a8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hargaKendaraan-Bekas</value>
      <webElementGuid>2c3f11ce-8cbe-4131-a287-5376177cc6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>curencyformat form-control</value>
      <webElementGuid>e63ecb96-ffd1-4450-9922-cd2b0b45cafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>8d72c833-f78a-4ca3-a83b-c041b7339600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hargaKendaraan-Bekas&quot;)</value>
      <webElementGuid>4da6f761-92ef-4698-808e-c653fb14da92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hargaKendaraan-Bekas']</value>
      <webElementGuid>38bd429a-59b0-417b-a239-e16839ee2881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobil-bekas']/div/div/div/input</value>
      <webElementGuid>7190492d-b66e-42cd-b071-0fb0e65c9dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>2adea0f3-9a7f-41d9-8423-2ffb5a58a23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Rp 0,00' and @id = 'hargaKendaraan-Bekas']</value>
      <webElementGuid>b3cf6a92-b8bd-462c-b5aa-db85a0d0690e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
