<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HitungSimulasi</name>
   <tag></tag>
   <elementGuidId>02afd41d-dbcc-4519-81c8-6cfa3db6d6a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-simulasiBudgetMobilBaru</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='jenisAsuransi-Baru']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9852cdfe-bdde-421c-bd38-2615b678c80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>green mt-3</value>
      <webElementGuid>b1865ff0-fed7-4ef0-a1b3-12e4dfd05664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-simulasiBudgetMobilBaru</value>
      <webElementGuid>275cc6a3-8d00-4c7e-9802-03fd16d5523f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung Simulasi</value>
      <webElementGuid>3688a4a5-f9b3-493a-974a-943b553f2e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-simulasiBudgetMobilBaru&quot;)</value>
      <webElementGuid>2bcde9f0-c2b2-4621-b833-6da075e2e236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-simulasiBudgetMobilBaru']</value>
      <webElementGuid>91e8270e-bfe9-4100-b6e3-eb0923096053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobil-baru']/button</value>
      <webElementGuid>e3b2cb2c-89a0-449a-9928-082ac684458a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zona Wilayah belum dipilih.'])[1]/following::button[1]</value>
      <webElementGuid>8757f800-0b71-40df-be54-015c0161e2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zona Wilayah'])[1]/following::button[1]</value>
      <webElementGuid>321d13d0-8836-422f-92ab-d38e5985c10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Kendaraan Mobil Bekas'])[1]/preceding::button[1]</value>
      <webElementGuid>2f79da39-f710-44b0-a2cd-6a978fd77964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silakan masukkan harga estimasi kendaraan'])[2]/preceding::button[1]</value>
      <webElementGuid>c3c6cbf5-fb4a-4abc-8f6e-c30a900ba0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hitung Simulasi']/parent::*</value>
      <webElementGuid>4407993d-9a55-46b5-85e8-63865279278b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/button</value>
      <webElementGuid>dd75e1e2-82af-49a1-93d6-46a3b13494f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-simulasiBudgetMobilBaru' and (text() = 'Hitung Simulasi' or . = 'Hitung Simulasi')]</value>
      <webElementGuid>bb1109ef-050b-49a7-85d6-cd2dbbee9bfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
