<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JenisAsuransi</name>
   <tag></tag>
   <elementGuidId>b3c8e6c5-4724-4525-85c3-121ffc5e7695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jenisAsuransi-Baru</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jenisAsuransi-Baru']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>047a5914-e428-4424-b2a1-e936c97f62de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asuransi</value>
      <webElementGuid>29abb2d5-02e0-4e20-a912-6373f1fae92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenisAsuransi-Baru</value>
      <webElementGuid>7f74f9a9-abaa-4211-b029-dff781e64c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a62a0ca6-28a0-4248-b497-b04a7b398ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Pilih Asuransi
                                                    Comprehensive
                                                    Combine
                                                    TLO
                                            </value>
      <webElementGuid>195b22ea-7eae-4008-a405-0df4e1a55d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenisAsuransi-Baru&quot;)</value>
      <webElementGuid>de2b96b3-614c-4849-8fae-a130de3ac7ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jenisAsuransi-Baru']</value>
      <webElementGuid>d0d1169e-2b09-40ad-931f-671ff18d72fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobil-baru']/div/div[5]/div/select</value>
      <webElementGuid>9a7fa231-4cf0-462e-9596-ed7511ca2f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Asuransi'])[1]/following::select[1]</value>
      <webElementGuid>147f4bfe-a7ab-4c94-a4f0-b4b46fce66b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uang Muka'])[2]/following::select[1]</value>
      <webElementGuid>907cf108-4afa-428a-a4a5-a1d4dd81e3dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asuransi Kendaraan belum dipilih.'])[1]/preceding::select[1]</value>
      <webElementGuid>9c51d525-8de9-4d23-bf74-78d743ca2f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zona Wilayah'])[1]/preceding::select[1]</value>
      <webElementGuid>e68470c8-1dd3-44a7-aa83-b33b3f1514e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>22e225ab-1715-4351-a432-09d2aeca71e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'asuransi' and @id = 'jenisAsuransi-Baru' and (text() = '
                                                Pilih Asuransi
                                                    Comprehensive
                                                    Combine
                                                    TLO
                                            ' or . = '
                                                Pilih Asuransi
                                                    Comprehensive
                                                    Combine
                                                    TLO
                                            ')]</value>
      <webElementGuid>b913586b-0987-412c-bcfa-5d93773beb40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
