<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JenisAsuransiBekas</name>
   <tag></tag>
   <elementGuidId>269c516a-d39c-4dc3-b076-dd9495a22754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jenisAsuransi-Bekas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jenisAsuransi-Bekas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5715b409-97c9-411c-b37b-2a2cc4c609b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asuransi</value>
      <webElementGuid>e3f0b79f-25e0-4648-a091-917ddeff079c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenisAsuransi-Bekas</value>
      <webElementGuid>730ec99e-d629-417f-a029-1a69bfda9dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5afc4f7b-42b5-4838-b990-bd3ee12e92d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Pilih Asuransi
                                                    Comprehensive
                                                    Combine
                                                    TLO
                                            </value>
      <webElementGuid>a99c69c2-f517-4fb6-9b2c-afe63404cc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenisAsuransi-Bekas&quot;)</value>
      <webElementGuid>5e945bc6-c2e0-4b50-8206-e51f000b5663</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jenisAsuransi-Bekas']</value>
      <webElementGuid>890124e1-80c4-4b38-b5a6-9f6b613d9c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobil-bekas']/div/div[6]/div/select</value>
      <webElementGuid>26816a97-750c-4897-9975-3241f3fab75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Asuransi'])[3]/following::select[1]</value>
      <webElementGuid>292a8d83-6bb0-442a-98c4-5e734a512cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uang Muka'])[4]/following::select[1]</value>
      <webElementGuid>e19fb4f7-5c03-4cc9-8835-cc84ed8ea7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asuransi Kendaraan belum dipilih.'])[2]/preceding::select[1]</value>
      <webElementGuid>2ceff715-d1c7-452b-a884-3700c451baac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zona Wilayah'])[2]/preceding::select[1]</value>
      <webElementGuid>3695aa04-b58b-4c9b-b1e5-04b9a69d039a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[6]/div/select</value>
      <webElementGuid>4f3c01f2-0786-4ada-a387-4464cf3bfa70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'asuransi' and @id = 'jenisAsuransi-Bekas' and (text() = '
                                                Pilih Asuransi
                                                    Comprehensive
                                                    Combine
                                                    TLO
                                            ' or . = '
                                                Pilih Asuransi
                                                    Comprehensive
                                                    Combine
                                                    TLO
                                            ')]</value>
      <webElementGuid>e2a51cd1-bc25-4207-88c8-0c62aad5048a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
