<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NavMobilBekas</name>
   <tag></tag>
   <elementGuidId>9dad5460-64cb-4306-a843-497c2943faa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-secondHand-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-secondHand-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4af1336f-36e4-48d2-aff2-1bcd5b7ba7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link</value>
      <webElementGuid>e2bbef32-b059-412a-9119-9df1216d6a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-secondHand-tab</value>
      <webElementGuid>de5f8483-f6f0-49d7-98f8-5153bd26682d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-conditionid</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>6fa33cae-a6d1-4a45-8b21-0491f27ed546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-condition</name>
      <type>Main</type>
      <value>Used</value>
      <webElementGuid>2dcd518d-80a8-4566-8839-27f0fe40576a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>026e0efa-5eae-475b-bdc9-bba31dcf2460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#mobil-bekas</value>
      <webElementGuid>b75a9f73-40c9-4b8f-aca3-85f669f6edbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>78282201-211d-46c2-91d4-e5f94c9eff1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>nav-secondHand</value>
      <webElementGuid>c3a78a0b-ab34-45f9-84b8-cb0d92a2b34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a3e8550d-7c49-4011-a65f-f6904df2f2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Mobil Bekas
                            </value>
      <webElementGuid>3af8c43a-de92-4534-911c-0f6efa785f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-secondHand-tab&quot;)</value>
      <webElementGuid>2d8147af-a95c-46dc-931f-b2b6d58fb86a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-secondHand-tab']</value>
      <webElementGuid>8dc5d52a-c8c0-46f9-9e5e-77d0262ffb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tab']/a[2]</value>
      <webElementGuid>a875707f-29b9-44ce-83b7-866f04f1a50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mobil Bekas')]</value>
      <webElementGuid>35b01cc8-3106-4173-a52e-3d529411e717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil Baru'])[1]/following::a[1]</value>
      <webElementGuid>11e65714-cfc6-40d9-b762-45f773ad297e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simulasi Budget'])[1]/following::a[2]</value>
      <webElementGuid>3e2f74f8-493c-4039-968f-7f037e0c9f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Kendaraan'])[1]/preceding::a[1]</value>
      <webElementGuid>305b9daf-a40a-40e4-9765-87c3a4df22ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silakan masukkan harga estimasi kendaraan'])[1]/preceding::a[1]</value>
      <webElementGuid>8937b02a-dc01-4d92-b8e0-d49ecfbd9408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobil Bekas']/parent::*</value>
      <webElementGuid>f0a51eda-5b59-4a6d-8c76-7a97f2119e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#mobil-bekas')]</value>
      <webElementGuid>486b46a8-5029-464c-851e-1672954976cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/nav/div/a[2]</value>
      <webElementGuid>05fe0d58-c4f1-4a0a-bc2a-c830313a4d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-secondHand-tab' and @href = '#mobil-bekas' and (text() = '
                                Mobil Bekas
                            ' or . = '
                                Mobil Bekas
                            ')]</value>
      <webElementGuid>8253953d-82c2-48ee-bd53-c76a7947c527</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
