<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NavMobilBaru</name>
   <tag></tag>
   <elementGuidId>1388b0e5-bea8-4b35-8e98-b2bc765aec11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-newCar-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-newCar-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dda478af-f091-4f65-8219-40f0afd4fb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link active</value>
      <webElementGuid>67903a9e-2158-4c08-aa1a-cb61fabb401f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-newCar-tab</value>
      <webElementGuid>8b31b48d-1367-4c81-94bf-edfa943f387a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-conditionid</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>4133a523-f18d-42cb-befe-543dc7aefb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-condition</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>9e82ca0f-1e84-4ee7-b2c3-f3c20ac02ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4240c298-bb50-4788-89e6-8e063a389389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#mobil-baru</value>
      <webElementGuid>264d6a05-bc52-430c-9b08-553d3a101f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b1d80180-f36e-4dba-a645-d583041e3aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>nav-newCar</value>
      <webElementGuid>89f1bcfb-8443-4e5f-b17f-c13de2a6a796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a835c739-fc1f-4e6f-9440-d43b79d4578f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Mobil Baru
                            </value>
      <webElementGuid>fb470b47-f542-4649-9026-b7bd43f47fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-newCar-tab&quot;)</value>
      <webElementGuid>12f23b5a-8ce5-4b5a-bb4a-4db3cabb18ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-newCar-tab']</value>
      <webElementGuid>f377f0b8-9f2f-4b69-8175-63aaf5c7b620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tab']/a</value>
      <webElementGuid>869ec95e-82e7-4644-9811-0c9005e927e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mobil Baru')]</value>
      <webElementGuid>5ccb87da-cb30-4ee1-badf-96aa54fbb6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simulasi Budget'])[1]/following::a[1]</value>
      <webElementGuid>3d0fe5ab-deea-486c-a1ef-293903618a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Astari Menjawab'])[1]/following::a[5]</value>
      <webElementGuid>c69480b0-fed5-4397-8d71-ec6243f24bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil Bekas'])[1]/preceding::a[1]</value>
      <webElementGuid>88507470-1861-42e1-997e-7b2b04600a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Kendaraan'])[1]/preceding::a[2]</value>
      <webElementGuid>bd19b7df-d3ff-4f70-bd84-b36def73ef7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobil Baru']/parent::*</value>
      <webElementGuid>8e399c7f-027e-4cd3-9ce9-1a1887f88720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#mobil-baru')]</value>
      <webElementGuid>5953e430-1ed9-41a2-a1fb-bd51383d67eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/nav/div/a</value>
      <webElementGuid>b6385a35-f7b7-4b6f-a381-4c29241c8d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-newCar-tab' and @href = '#mobil-baru' and (text() = '
                                Mobil Baru
                            ' or . = '
                                Mobil Baru
                            ')]</value>
      <webElementGuid>55935023-0049-49d9-8d03-1411d8a3afca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
