<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TahunKendaraanBekas</name>
   <tag></tag>
   <elementGuidId>a950224a-04da-47f4-b76e-eb3221a9e7fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tahunKendaraan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tahunKendaraan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04a31844-cbad-4cfb-818b-062744c8adbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93f06f96-e504-4d71-bed4-3eac76c9a160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tahunKendaraan</value>
      <webElementGuid>a2962b28-abad-4074-b7a5-e46e482d35d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>204b9461-82b5-489e-ae65-0b18672dfa40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>db9af521-4a0f-4073-9e9f-0d1851c5cde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tahunKendaraan&quot;)</value>
      <webElementGuid>ef597807-abee-43dd-9810-83df9a8e55bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tahunKendaraan']</value>
      <webElementGuid>de470163-d870-47e6-8fc7-7379ecc96417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobil-bekas']/div/div[2]/div/input</value>
      <webElementGuid>444b5f77-8975-4db6-b934-f76a679f4625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>36786c9f-2799-40ca-816c-3c3192d377fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tahunKendaraan']</value>
      <webElementGuid>d8a62c8a-7811-4939-99a8-373a7f88d4fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
