<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UangMuka</name>
   <tag></tag>
   <elementGuidId>6a4c1592-1c83-4f24-bc2f-28da8121b8a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#budget-Baru</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='budget-Baru']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2bcd2a5-538f-42f4-91b6-205c7679d8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4affa36-f3cc-4a61-9b94-392f718956d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>18952ca8-686d-475f-8d61-f838384e1897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>budget-Baru</value>
      <webElementGuid>12601359-edf4-4069-a178-70a012b8a760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rp 0,00</value>
      <webElementGuid>bd510c99-6905-42a4-b86f-4facbbd28c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>curencyformat form-control</value>
      <webElementGuid>8837a1f7-0879-4998-bb20-0a5799f27c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;budget-Baru&quot;)</value>
      <webElementGuid>28a596aa-4075-4d1d-a8cd-dc400d0653cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='budget-Baru']</value>
      <webElementGuid>c1c2c342-0a06-4518-86df-5ea38db3578a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobil-baru']/div/div[4]/div/input</value>
      <webElementGuid>d0797c0f-bc43-43cf-bb8e-3a059d68e638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>71ee6ff0-09d9-4efe-a0a4-ee73f0105c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'budget-Baru' and @placeholder = 'Rp 0,00']</value>
      <webElementGuid>2d66d162-7f21-41de-8a7c-33f5208921d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
