<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UangMukaBekas</name>
   <tag></tag>
   <elementGuidId>756512a2-cdac-4435-9f88-411ffac8b400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#budget-Bekas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='budget-Bekas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7de265cb-6956-4e10-89b6-a5599ebe0bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e35a9dd7-9ca8-4e47-b0e2-e8feab535dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>budget-Bekas</value>
      <webElementGuid>a4334be2-3069-4ac4-98ae-c88beeea536a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>fea67f8e-68a6-43d1-b8f8-b6265518460c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rp 0,00</value>
      <webElementGuid>33d836a2-e1c0-422d-8974-07c128712e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>curencyformat form-control</value>
      <webElementGuid>f750d400-5f09-4865-8917-1ebb949de60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;budget-Bekas&quot;)</value>
      <webElementGuid>b5e5ee16-2016-4b20-aabe-bc54ab52f40c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='budget-Bekas']</value>
      <webElementGuid>030a9b07-f741-4db2-ba77-cd1640e495ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobil-bekas']/div/div[5]/div/input</value>
      <webElementGuid>9d9f6046-bd75-42de-b7b9-2278d34fa8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>4f6a08bd-87e7-4968-b6f2-6dc8ab262635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'budget-Bekas' and @placeholder = 'Rp 0,00']</value>
      <webElementGuid>69c02934-d750-46b4-b37d-0d53a7d001be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
